# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://xiaochu.cf
date_format: "ordinal"
title: chu
subtitle: "少点完美，多点产出"
description: "chu 的个人博客"
keywords: chu
timezone: Asia/Guanddong
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: chu
organization: 
organization_url: 
github_username: jiujiubad
location: ShenZhen, China
email: jiujiubad@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown #使用kramdown做代码语法高亮
kramdown:
    input: GFM     #启用github的markdown语法
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap     #生成sitemap
    - jekyll-feed
    - jemoji             #允许标签
#     - jekyll-mentions  #允许"@ somebody"
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jiujiubad/https://github.com/jiujiubad/chu-mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: valine + valine-admin > gitalk > gitment > livere > 畅言
comments_provider: valine_comment  #选用一个评论工具
# valine官方，https://valine.js.org/quickstart.html
# valine-admin官方，https://github.com/DesertsP/Valine-Admin
valine_comment:
    enable: true
    leancloud_appid: FHb8aJ7oAcDl26IuPtRv9lPn-gzGzoHsz
    leancloud_appkey: nBnidzcikGtDKHFvyUBM9PG9
    placeholder: "说点什么吧..."
    visitor: true     #阅读量统计，https://valine.js.org/visitor.html
    avatar: mp        #头像，https://valine.js.org/avatar.html
    notify: false     #评论回复时邮件提醒，https://github.com/xCss/Valine/wiki
    verify: false     #验证码
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 20

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

theme: jekyll-theme-cayman